# Generated by Django 5.2.4 on 2025-09-11 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorize', '0002_department_alter_userlog_action_setaudio_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อแพ็กเกจ')),
                ('duration_years', models.IntegerField(default=1, verbose_name='อายุการใช้งาน (ปี)')),
                ('features', models.JSONField(default=dict, verbose_name='สิทธิ์การใช้งาน')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'license',
                'db_table': 'tb_license',
            },
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license', verbose_name='License')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorize.userprofile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'user_license',
                'db_table': 'tb_userlicense',
            },
        ),
    ]
